<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>LOGOGUARD.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="srcBACKUP\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="NFA\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="LOGOGUARD.ico" />
  </ItemGroup>

</Project>
